### ISSUE TITLE
GNB 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_OWNER#17]
## Tasks
- [ ] 각 메뉴 아이콘 삽입
- [ ] 각 메뉴 라벨 삽입
- [ ] padding 값 설정 (x: 32px, bottom: 24px)
