### ISSUE TITLE
molecule: RecentCarwashItem 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_OWNER#20]
홈화면 콘텐츠 중 가장 하단에 위치한 최근 이용 내역에 표시되는 아이템

## Tasks
- [ ] Photo 컴포넌트 활용하여 세차장 이미지 삽입
- [ ] 날짜와 세차장명 표시
- [ ] tailwind 스타일 추가
