### ISSUE TITLE
atom: TimeTable 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_OWNER#46]
## Description
<img width="993" alt="Screenshot 2023-10-16 at 2 06 28 PM" src="https://github.com/Step3-kakao-tech-campus/Team10_FE_OWNER/assets/104883910/d5c3d0d8-22c9-469f-94bf-128b5a94bddb">
매장관리 페이지에서 매장별로 예약현황을 보여주는 시간표 컴포넌트

## Tasks
- [x] table 태그로 구현
- [x] 예약된 시간은 파란색(primary color)로 칸 채우기
- [x] 운영시간에 따라 표시 시간 달라짐 (ex. 운영시간이 07:00~22:00이면 07시부터 21시까지 표시)
