### ISSUE TITLE
organism: CarwashItem 컴포넌트 구현

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_OWNER#48]
## Description
<img width="1149" alt="Screenshot 2023-10-16 at 2 19 36 PM" src="https://github.com/Step3-kakao-tech-campus/Team10_FE_OWNER/assets/104883910/4d820560-6c23-49ab-b2e9-ef3535bdcc97">
매장관리 페이지 오른쪽 section에 표시되는 개별 매장 아이템

## Tasks
- [x] 왼쪽 192*192 크기의 매장사진 표시
- [x] 오른쪽 제목 영역은 24px, bold, padding-16px
- [x] 아래쪽 내용 영역에 MultipleTimeTable 컴포넌트 표시
