### ISSUE TITLE
CarwashItem 안에 내용이 많아지면 사진 배치가 어색해지는 현상

### ISSUE THREAD

**Issue by juyeongnoh** [Step3-kakao-tech-campus/Team10_FE_OWNER#58]
## Description
<img width="1269" alt="Screenshot 2023-10-17 at 3 47 42 PM" src="https://github.com/Step3-kakao-tech-campus/Team10_FE_OWNER/assets/104883910/a1a4e803-3b1e-4f08-a82f-f634e3e170ca">

CarwashItem 내 MultipleTimeTable 컴포넌트가 수직으로 길어지면 왼쪽 세차장 사진의 배치가 어색해지는 현상이 있습니다.
사진 크기가 고정 (192*192)이라 발생하는 현상으로 보입니다.

## Tasks
- [ ] img 태그를 div 태그로 감싸기
- [ ] Carwash 컴포넌트가 수직으로 길어지더라도 width는 192px로 고정, 세로로만 늘어나게 수정
- [ ] 사진이 어색하게 확대되지 않고 비율을 유지하며 div를 가득 채우게 수정
